name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - linux-musl-arm
          - linux-musl-arm64
          - linux-musl-x64
          - osx-arm64
          - osx-x64
          - win-arm
          - win-arm64
          - win-x64
          - win-x86

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build the program
        run: |
          dotnet publish src -c Release -o build --sc false -r ${{ matrix.runtime }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: novelcraft-agent-${{ matrix.runtime }}
          path: build

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: agent:latest
